export type User = {
  id?: string;
  companyName: string;
  representativeName: string;
  companyRut?: string;
  password?: string;
  email: string;
  phone?: string;
  address?: string;
  city?: string;
  comuna_id: string | number;
  region?: string;
  country?: string;
  imageUrl?: string;
  created_at?: string;
  token?: string;
  role?: string;
  comunas?: string;
  offers_free_meet_greet?: boolean;
};
