export const allComunas = [
  'ALGARROBO',
  'ALHUE',
  'ALTO BIOBIO',
  'ALTO DEL CARMEN',
  'ALTO HOSPICIO',
  'ANCUD',
  'ANDACOLLO',
  'ANGOL',
  'ANTOFAGASTA',
  'ANTUCO',
  'ARAUCO',
  'ARICA',
  'AYSEN',
  'BUIN',
  'BULNES',
  'CABILDO',
  'CABO DE HORNOS',
  'CABRERO',
  'CALAMA',
  'CALBUCO',
  'CALDERA',
  'CALERA DE TANGO',
  'CALLE LARGA',
  'CAMARONES',
  'CAMINA',
  'CANELA',
  'CANETE',
  'CARAHUE',
  'CARTAGENA',
  'CASABLANCA',
  'CASTRO',
  'CATEMU',
  'CAUQUENES',
  'CERRILLOS',
  'CERRO NAVIA',
  'CHAITEN',
  'CHANARAL',
  'CHANCO',
  'CHEPICA',
  'CHIGUAYANTE',
  'CHILE CHICO',
  'CHILLAN',
  'CHILLAN VIEJO',
  'CHIMBARONGO',
  'CHOLCHOL',
  'CHONCHI',
  'CISNES',
  'COBQUECURA',
  'COCHAMO',
  'COCHRANE',
  'CODEGUA',
  'COELEMU',
  'COIHUECO',
  'COINCO',
  'COLBUN',
  'COLCHANE',
  'COLINA',
  'COLLIPULLI',
  'COLTAUCO',
  'COMBARBALA',
  'CONCEPCION',
  'CONCHALI',
  'CONCON',
  'CONSTITUCION',
  'CONTULMO',
  'COPIAPO',
  'COQUIMBO',
  'CORONEL',
  'CORRAL',
  'COYHAIQUE',
  'CUNCO',
  'CURACAUTIN',
  'CURACAVI',
  'CURACO DE VELEZ',
  'CURANILAHUE',
  'CURARREHUE',
  'CUREPTO',
  'CURICO',
  'DALCAHUE',
  'DIEGO DE ALMAGRO',
  'DONIHUE',
  'EL BOSQUE',
  'EL CARMEN',
  'EL MONTE',
  'EL QUISCO',
  'EL TABO',
  'EMPEDRADO',
  'ERCILLA',
  'ESTACION CENTRAL',
  'FLORIDA',
  'FREIRE',
  'FREIRINA',
  'FRESIA',
  'FRUTILLAR',
  'FUTALEUFU',
  'FUTRONO',
  'GALVARINO',
  'GENERAL LAGOS',
  'GORBEA',
  'GRANEROS',
  'GUAITECAS',
  'HIJUELAS',
  'HUALAIHUE',
  'HUALANE',
  'HUALPEN',
  'HUALQUI',
  'HUARA',
  'HUASCO',
  'HUECHURABA',
  'ILLAPEL',
  'INDEPENDENCIA',
  'IQUIQUE',
  'ISLA DE MAIPO',
  'ISLA DE PASCUA',
  'JUAN FERNANDEZ',
  'LA CALERA',
  'LA CISTERNA',
  'LA CRUZ',
  'LA ESTRELLA',
  'LA FLORIDA',
  'LA GRANJA',
  'LA HIGUERA',
  'LA LIGUA',
  'LA PINTANA',
  'LA REINA',
  'LA SERENA',
  'LA UNION',
  'LAGO RANCO',
  'LAGO VERDE',
  'LAGUNA BLANCA',
  'LAJA',
  'LAMPA',
  'LANCO',
  'LAS CABRAS',
  'LAS CONDES',
  'LAUTARO',
  'LEBU',
  'LICANTEN',
  'LIMACHE',
  'LINARES',
  'LITUECHE',
  'LLANQUIHUE',
  'LLAY-LLAY',
  'LO BARNECHEA',
  'LO ESPEJO',
  'LO PRADO',
  'LOLOL',
  'LONCOCHE',
  'LONGAVI',
  'LONQUIMAY',
  'LOS ALAMOS',
  'LOS ANDES',
  'LOS ANGELES',
  'LOS LAGOS',
  'LOS MUERMOS',
  'LOS SAUCES',
  'LOS VILOS',
  'LOTA',
  'LUMACO',
  'MACHALI',
  'MACUL',
  'MAFIL',
  'MAIPU',
  'MALLOA',
  'MARIA ELENA',
  'MARIA PINTO',
  'MARIQUINA',
  'MAULE',
  'MAULLIN',
  'MEJILLONES',
  'MELIPEUCO',
  'MELIPILLA',
  'MOLINA',
  'MONTE PATRIA',
  'MULCHEN',
  'NACIMIENTO',
  'NANCAGUA',
  'NATALES',
  'NAVIDAD',
  'NEGRETE',
  'NINHUE',
  'NIQUEN',
  'NOGALES',
  'NUEVA IMPERIAL',
  'NUNOA',
  'OHIGGINS',
  'OLIVAR',
  'OLLAGUE',
  'OLMUE',
  'OSORNO',
  'OVALLE',
  'PADRE HURTADO',
  'PADRE LAS CASAS',
  'PAIHUANO',
  'PAILLACO',
  'PAINE',
  'PALENA',
  'PALMILLA',
  'PANGUIPULLI',
  'PANQUEHUE',
  'PAPUDO',
  'PAREDONES',
  'PARRAL',
  'PEDRO AGUIRRE CERDA',
  'PELARCO',
  'PELLUHUE',
  'PEMUCO',
  'PENAFLOR',
  'PENALOLEN',
  'PENCAHUE',
  'PENCO',
  'PERALILLO',
  'PERQUENCO',
  'PETORCA',
  'PEUMO',
  'PICA',
  'PICHIDEGUA',
  'PICHILEMU',
  'PINTO',
  'PIRQUE',
  'PITRUFQUEN',
  'PLACILLA',
  'PORTEZUELO',
  'PORVENIR',
  'POZO ALMONTE',
  'PRIMAVERA',
  'PROVIDENCIA',
  'PUCHUNCAVI',
  'PUCON',
  'PUDAHUEL',
  'PUENTE ALTO',
  'PUERTO MONTT',
  'PUERTO OCTAY',
  'PUERTO VARAS',
  'PUMANQUE',
  'PUNITAQUI',
  'PUNTA ARENAS',
  'PUQUELDON',
  'PUREN',
  'PURRANQUE',
  'PUTAENDO',
  'PUTRE',
  'PUYEHUE',
  'QUEILEN',
  'QUELLON',
  'QUEMCHI',
  'QUILACO',
  'QUILICURA',
  'QUILLECO',
  'QUILLON',
  'QUILLOTA',
  'QUILPUE',
  'QUINCHAO',
  'QUINTA DE TILCOCO',
  'QUINTA NORMAL',
  'QUINTERO',
  'QUIRIHUE',
  'RANCAGUA',
  'RANQUIL',
  'RAUCO',
  'RECOLETA',
  'RENAICO',
  'RENCA',
  'RENGO',
  'REQUINOA',
  'RETIRO',
  'RINCONADA',
  'RIO BUENO',
  'RIO CLARO',
  'RIO HURTADO',
  'RIO IBANEZ',
  'RIO NEGRO',
  'RIO VERDE',
  'ROMERAL',
  'SAAVEDRA',
  'SAGRADA FAMILIA',
  'SALAMANCA',
  'SAN ANTONIO',
  'SAN BERNARDO',
  'SAN CARLOS',
  'SAN CLEMENTE',
  'SAN ESTEBAN',
  'SAN FABIAN',
  'SAN FELIPE',
  'SAN FERNANDO',
  'SAN FRANCISCO DE MOSTAZAL',
  'SAN GREGORIO',
  'SAN IGNACIO',
  'SAN JAVIER',
  'SAN JOAQUIN',
  'SAN JOSE DE MAIPO',
  'SAN JUAN DE LA COSTA',
  'SAN MIGUEL',
  'SAN NICOLAS',
  'SAN PABLO',
  'SAN PEDRO',
  'SAN PEDRO DE ATACAMA',
  'SAN PEDRO DE LA PAZ',
  'SAN RAFAEL',
  'SAN RAMON',
  'SAN ROSENDO',
  'SAN VICENTE',
  'SANTA BARBARA',
  'SANTA CRUZ',
  'SANTA JUANA',
  'SANTA MARIA',
  'SANTIAGO',
  'SANTIAGO OESTE',
  'SANTIAGO SUR',
  'SANTO DOMINGO',
  'SIERRA GORDA',
  'TALAGANTE',
  'TALCA',
  'TALCAHUANO',
  'TALTAL',
  'TEMUCO',
  'TENO',
  'TEODORO SCHMIDT',
  'TIERRA AMARILLA',
  'TIL-TIL',
  'TIMAUKEL',
  'TIRUA',
  'TOCOPILLA',
  'TOLTEN',
  'TOME',
  'TORRES DEL PAINE',
  'TORTEL',
  'TRAIGUEN',
  'TREHUACO',
  'TUCAPEL',
  'VALDIVIA',
  'VALLENAR',
  'VALPARAISO',
  'VICHUQUEN',
  'VICTORIA',
  'VICUNA',
  'VILCUN',
  'VILLA ALEGRE',
  'VILLA ALEMANA',
  'VILLARRICA',
  'VINA DEL MAR',
  'VITACURA',
  'YERBAS BUENAS',
  'YUMBEL',
  'YUNGAY',
  'ZAPALLAR',
];

export const availability = [
  {
    id: 1,
    name: 'Lunes',
  },
  {
    id: 2,
    name: 'Martes',
  },
  {
    id: 3,
    name: 'Miercoles',
  },
  {
    id: 4,
    name: 'Jueves',
  },
  {
    id: 5,
    name: 'Viernes',
  },
  {
    id: 6,
    name: 'Sabado',
  },
  {
    id: 7,
    name: 'Domingo',
  },
];

export type Prestador = {
  firstname: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  state: string;
  country: string;
  comunas: string[];
  service: string;
  speciality: string;
  profile_pic: string;
  availability: string[];
};

export type Service = {
  id: number;
  text: string;
  speciality: {
    id: number;
    text: string;
  }[];
};

export const dummyPrestadores: Prestador[] = [
  {
    firstname: 'Juan',
    email: 'juan@prestador1.com',
    phone: '1234551234',
    address: '423 Julio Prado',
    city: 'Santiago',
    state: 'Metropolitana',
    country: 'Chile',
    comunas: ['SANTIAGO', 'PROVIDENCIA', 'LAS CONDES'],
    service: 'Soporte Terapéutico',
    speciality: 'Kinesiología',
    profile_pic: 'https://icon-library.com/images/google-user-icon/google-user-icon-7.jpg',
    availability: ['1', '2', '3', '4', '5', '6', '7'],
  },
  {
    firstname: 'Pedro',
    email: 'pedro@prestador1.com',
    phone: '1234551234',
    address: '423 Julio Prado',
    city: 'Rancagua',
    state: 'Sexta Region',
    country: 'Chile',
    comunas: ['MACHALI', 'RANCAGUA'],
    service: 'Soporte Terapéutico',
    speciality: 'Fonoaudiología',
    profile_pic:
      'https://cambodiaict.net/wp-content/uploads/2019/12/computer-icons-user-profile-google-account-photos-icon-account.jpg',
    availability: ['4', '5', '6', '7'],
  },
];

export const services = [
  {
    id: 1,
    text: 'Apoyo en el hogar',
    speciality: [
      {
        id: 1,
        text: 'Apoyo en el hogar',
      },
    ],
  },
  {
    id: 2,
    text: 'Cuidadora',
    speciality: [
      {
        id: 2,
        text: 'Cuidadora',
      },
    ],
  },
  {
    id: 3,
    text: 'Soporte Terapéutico',
    speciality: [
      {
        id: 1,
        text: 'Kinesiología',
      },
      {
        id: 2,
        text: 'Quiropráctica',
      },
      {
        id: 3,
        text: 'Odontología',
      },
      {
        id: 4,
        text: 'Fonoaudiología',
      },
      {
        id: 5,
        text: 'Podología',
      },
      {
        id: 6,
        text: 'Psicología',
      },
      {
        id: 7,
        text: 'Terapeuta Ocupacional',
      },
    ],
  },
  {
    id: 4,
    text: 'Servicios de enfermería',
    speciality: [
      {
        id: 1,
        text: 'Enfermería',
      },
      {
        id: 2,
        text: 'Técnico en enfermería',
      },
    ],
  },
  {
    id: 5,
    text: 'Sana compañía',
    speciality: [
      {
        id: 1,
        text: 'Sana compañía',
      },
    ],
  },
];

export const days = [
  {
    id: 1,
    name: 'Lunes',
  },
  {
    id: 2,
    name: 'Martes',
  },
  {
    id: 3,
    name: 'Miercoles',
  },
  {
    id: 4,
    name: 'Jueves',
  },
  {
    id: 5,
    name: 'Viernes',
  },
  {
    id: 6,
    name: 'Sabado',
  },
  {
    id: 7,
    name: 'Domingo',
  },
];
